/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ci.cd._demo;

import org.testng.annotations.*;
import static org.testng.Assert.*;

public class AppTest {
    @Test
    public void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
//hello sharat try out workflow
    //se cond test of workflow
}
